"""empty message

Revision ID: 578c00890a64
Revises: 888ad860d221
Create Date: 2019-01-31 09:24:00.524436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '578c00890a64'
down_revision = '888ad860d221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    op.drop_column('users', 'emial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emial', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
