"""empty message

Revision ID: 82f2af2ab246
Revises: 578c00890a64
Create Date: 2019-01-31 09:46:23.856456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82f2af2ab246'
down_revision = '578c00890a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=mysql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
