"""empty message

Revision ID: 888ad860d221
Revises: 
Create Date: 2019-01-30 11:39:18.853709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888ad860d221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('co_id', sa.Integer(), nullable=False),
    sa.Column('co_name', sa.String(length=200), nullable=False),
    sa.Column('co_new_price', sa.Float(precision=50), nullable=False),
    sa.Column('co_old_price', sa.Float(precision=50), nullable=False),
    sa.Column('co_img', sa.String(length=200), nullable=False),
    sa.Column('co_information', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('co_id')
    )
    op.create_table('company_information',
    sa.Column('cpy_id', sa.Integer(), nullable=False),
    sa.Column('cpy_num', sa.Integer(), nullable=False),
    sa.Column('cpy_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('cpy_id')
    )
    op.create_table('user_class',
    sa.Column('uc_id', sa.Integer(), nullable=False),
    sa.Column('uc_svip', sa.Integer(), nullable=True),
    sa.Column('uc_vip', sa.Integer(), nullable=True),
    sa.Column('uc_nvip', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uc_id')
    )
    op.create_table('back_to_buy',
    sa.Column('btb_id', sa.Integer(), nullable=False),
    sa.Column('btb_text', sa.Text(), nullable=False),
    sa.Column('btb_co_infor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['btb_co_infor_id'], ['commodity.co_id'], ),
    sa.PrimaryKeyConstraint('btb_id')
    )
    op.create_table('department_information',
    sa.Column('dt_id', sa.Integer(), nullable=False),
    sa.Column('dt_num', sa.Integer(), nullable=False),
    sa.Column('dt_name', sa.String(length=200), nullable=False),
    sa.Column('dt_cpy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dt_cpy_id'], ['company_information.cpy_id'], ),
    sa.PrimaryKeyConstraint('dt_id')
    )
    op.create_table('impower',
    sa.Column('im_id', sa.Integer(), nullable=False),
    sa.Column('im_num', sa.Integer(), nullable=False),
    sa.Column('im_information', sa.String(length=500), nullable=False),
    sa.Column('im_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['im_class_id'], ['user_class.uc_id'], ),
    sa.PrimaryKeyConstraint('im_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_password', sa.String(length=32), nullable=False),
    sa.Column('user_mobile', sa.String(length=11), nullable=False),
    sa.Column('head_portrait', sa.String(length=30), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.Time(), nullable=False),
    sa.Column('emial', sa.String(length=200), nullable=True),
    sa.Column('if_online', sa.Boolean(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=200), nullable=True),
    sa.Column('last_login_time', sa.Time(), nullable=True),
    sa.Column('user_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_class_id'], ['user_class.uc_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('estimate',
    sa.Column('est_id', sa.Integer(), nullable=False),
    sa.Column('est_text', sa.Text(), nullable=False),
    sa.Column('est_img', sa.String(length=200), nullable=True),
    sa.Column('est_class', sa.Integer(), nullable=False),
    sa.Column('est_user_id', sa.Integer(), nullable=True),
    sa.Column('est_co_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['est_co_id'], ['commodity.co_id'], ),
    sa.ForeignKeyConstraint(['est_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('est_id')
    )
    op.create_table('shopping',
    sa.Column('s_car_id', sa.Integer(), nullable=False),
    sa.Column('of_co_name', sa.Integer(), nullable=False),
    sa.Column('s_car_infor_id', sa.Integer(), nullable=True),
    sa.Column('s_car_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['s_car_infor_id'], ['commodity.co_id'], ),
    sa.ForeignKeyConstraint(['s_car_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('s_car_id')
    )
    op.create_table('staff_information',
    sa.Column('st_id', sa.Integer(), nullable=False),
    sa.Column('st_num', sa.Integer(), nullable=False),
    sa.Column('st_name', sa.String(length=200), nullable=False),
    sa.Column('st_position', sa.String(length=200), nullable=False),
    sa.Column('st_cpy_id', sa.Integer(), nullable=True),
    sa.Column('st_dt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['st_cpy_id'], ['company_information.cpy_id'], ),
    sa.ForeignKeyConstraint(['st_dt_id'], ['department_information.dt_id'], ),
    sa.PrimaryKeyConstraint('st_id')
    )
    op.create_table('take_information',
    sa.Column('ta_id', sa.Integer(), nullable=False),
    sa.Column('ta_name', sa.String(length=50), nullable=False),
    sa.Column('ta_address', sa.String(length=200), nullable=False),
    sa.Column('ta_tel', sa.String(length=11), nullable=False),
    sa.Column('ta_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ta_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ta_id')
    )
    op.create_table('order_form',
    sa.Column('of_id', sa.Integer(), nullable=False),
    sa.Column('of_co_num', sa.Integer(), nullable=False),
    sa.Column('of_co_infor', sa.Integer(), nullable=True),
    sa.Column('of_user_id', sa.Integer(), nullable=True),
    sa.Column('of_ta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['of_co_infor'], ['commodity.co_id'], ),
    sa.ForeignKeyConstraint(['of_ta_id'], ['take_information.ta_id'], ),
    sa.ForeignKeyConstraint(['of_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('of_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_form')
    op.drop_table('take_information')
    op.drop_table('staff_information')
    op.drop_table('shopping')
    op.drop_table('estimate')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('impower')
    op.drop_table('department_information')
    op.drop_table('back_to_buy')
    op.drop_table('user_class')
    op.drop_table('company_information')
    op.drop_table('commodity')
    # ### end Alembic commands ###
